#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 20 19:48:20 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.4 + Colorwheel_0.2.1
