ServerEvents.recipes(event =>{
event.shapeless('farmingtales:beer_wheat_ingredients',[
"brewery:hops",
"brewery:dried_wheat",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:beer_barley_ingredients',[
"brewery:hops",
"brewery:dried_barley",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:beer_hops_ingredients',[
"brewery:hops",
"brewery:hops",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:beer_oat_ingredients',[
"brewery:hops",
"brewery:dried_oat",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:beer_nettle_ingredients',[
"brewery:hops",
"farm_and_charm:wild_nettle",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:beer_haley_ingredients',[
"brewery:hops",
"minecraft:popped_chorus_fruit",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_jo_jannik_ingredients',[
"brewery:dried_barley",
"brewery:dried_barley",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_lilitu_single_malt_ingredients',[
"brewery:dried_wheat",
"brewery:dried_barley",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_cristel_walker_ingredients',[
"brewery:dried_corn",
"brewery:dried_corn",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_maggoallan_ingredients',[
"brewery:dried_wheat",
"brewery:dried_wheat",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_carrascon_label_ingredients',[
"brewery:dried_wheat",
"brewery:dried_corn",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_ak_ingredients',[
"brewery:dried_oat",
"brewery:dried_corn",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_highland_hearth_ingredients',[
"brewery:dried_oat",
"brewery:dried_wheat",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_smoky_reverie_ingredients',[
"brewery:dried_oat",
"brewery:dried_oat",
"farm_and_charm:yeast"
])
event.shapeless('farmingtales:whiskey_jamesons_malt_ingredients',[
"brewery:dried_oat",
"brewery:dried_barley",
"farm_and_charm:yeast"
])
})