#填入对应实体的ID可以防止被蛇发女妖石化
excluded_entity_ids = [
    "minecraft:giant",
    "iceandfire:firedragon",
    "iceandfire:icedragon",
    "iceandfire:lightning_dragon",
    "somebosses:aesegull",
    "somebosses:prismarine_watcher",
    "somebosses:froverlord",
    "somebosses:volcanium",
    "somebosses:merciless_assasin",
    "somebosses:dark_mask",
    "somebosses:knight_garent",
    "somebosses:vulcan",
    "somebosses:ancient_wizard",
    "somebosses:man_of_water",
    "somebosses:flaming_berserker",
    "somebosses:electric_head",
    "somebosses:frost_magma",
    "somebosses:stone_guard",
    "somebosses:crimson_vampire",
    "somebosses:skeleton_demon",
    "somebosses:mono_eyed_skeleton",
    "somebosses:hand_head",
    "somebosses:ender_ordnance",
    "somebosses:nameless_one",
    "somebosses:sand_giant",
    "somebosses:rib_golem",
    "cataclysm:netherite_monstrosity",
    "cataclysm:ender_guardian",
    "cataclysm:ignis",
    "cataclysm:the_harbinger",
    "cataclysm:the_leviathan",
    "cataclysm:ancient_remnant",
    "bosses_of_mass_destruction:void_blossom",
    "bosses_of_mass_destruction:lich",
    "bosses_of_mass_destruction:gauntlet",
    "bosses_of_mass_destruction:obsidilith",
    "meetyourfight:bellringer",
    "meetyourfight:rosalyne",
    "meetyourfight:swampjaw",
    "meetyourfight:dame_fortuna",
    "invasioncodered:gashslit",
    "irons_spellbooks:dead_king_corpse",
    "goety:apostle",
    "goety:vizier",
    "graveyard:lich",
    "minecraft:ender_dragon",
    "minecraft:wither",
    "twilightforest:naga",
    "twilightforest:lich",
    "twilightforest:hydra",
    "twilightforest:ur_ghast",
    "twilightforest:snow_queen",
    "twilightforest:knight_phantom",
    "twilightforest:minoshroom"
]

